### ISSUE TITLE
add CI

### ISSUE THREAD

**Issue by rursprung** [bnbhat/bno08x_ros2_driver#2]
i'd suggest to add a CI to ensure that the repo will always build and passes all builds (see #1).

you can e.g. use this GH CI workflow which works fine for me:

```yaml
name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test-ros:
    name: Build and test ROS nodes
    runs-on: ubuntu-latest
    container:
      image: ros:jazzy
    steps:
      - uses: actions/checkout@v4
        with:
          # ROS expects the sources in a workspace to be in `src` - we can use the checkout folder as the workspace folder
          path: src
      - name: Install Prerequisites
        run: |
          bash -c 'source /opt/ros/$ROS_DISTRO/setup.bash; \
          apt-get update && apt-get upgrade -y && apt-get install ros-dev-tools -y && rosdep update; \
          rosdep install --from-paths src --ignore-src -y'
      - name: Build Workspace
        run: |
          bash -c 'source /opt/ros/$ROS_DISTRO/setup.bash; \
          colcon build'
      - name: Run Tests
        run: |
          bash -c 'source /opt/ros/$ROS_DISTRO/setup.bash; \
          colcon test; \
          colcon test-result --verbose'

  # simplify GH settings: have one single build to be required
  build-results:
    name: Final Results
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs:
      - build-and-test-ros
    steps:
      - name: "check for failed builds"
        run: |
          cat <<EOF | jq -e 'unique | all(. == "success")'
          ${{ toJson(needs.*.result) }}
          EOF
```

this has been clobbered together from various other ROS workflows i've found on GH.

then you can set `build-results` as a required status check for all PRs (advantage of using this indirection: you can always add more workflows and just list them as needed in `build-results` and don't have to change the GH settings).
